Add helper method for fixed APR
element-fi/elf-sdk pull request #24
Opened 2021-07-14 19:20 UTC by smmackey

Adds a helper to calculate fixed APR given spot price. Included an example script for usage, essentially a copy of the spot price example

2021-07-14 20:58 UTC, jrhea requested changes
Love this!  Just a couple of suggested mods

2021-07-14 20:58 UTC, jrhea commented on examples/fixedAPR.ts
> +  console.log(`fixedAPR: ${fixedAPR}`);
this is great that you made an example!  It would probably make sense to just roll the fixedAPR calc into the spotPrice example.  I think we could rename that example from spotPrice.ts to poolDetails.ts or something like that.

2021-07-14 20:58 UTC, jrhea commented on test/calcFixedAprTest.ts
> +// } from "../src/constants/time";
lets delete this if it isn't needed

2021-07-14 21:20 UTC, smmackey commented on test/calcFixedAprTest.ts
> +// } from "../src/constants/time";
Good catch, removed it!

2021-07-14 21:20 UTC, smmackey commented on examples/fixedAPR.ts
> +  console.log(`fixedAPR: ${fixedAPR}`);
Makes sense! I combined then, updated the ReadMe's example command to reflect that

2021-07-14 22:32 UTC, sentilesdal commented on src/helpers/calcFixedAPR.ts
> +): number {
let's add safeguards for when timeUntilMaturity is zero or less than zero and also unit tests for those cases.  if timeUntilMaturity < 0, then fixedAPR is zero, not some negative value.

2021-07-14 22:32 UTC, sentilesdal commented on src/helpers/calcFixedAPR.ts
> +  timeUntilMaturity: number
I'd probably make this 'secondsUntilMaturity' to give a hint at units.

2021-07-14 22:32 UTC, sentilesdal commented on test/calcFixedAprTest.ts
> +    const timeUntilMaturity = 89 / 365;
so this makes sense to me, but in the example you are passing timeRemainingInSeconds.  I think passing timeRemainingInSeconds feels more natural and the helper can figure out how much a year that is.

2021-07-15 16:10 UTC, smmackey commented on test/calcFixedAprTest.ts
> +    const timeUntilMaturity = 89 / 365;
Good point, added that edit. It's a little more uniform with the spot price method this way too

2021-07-15 16:10 UTC, smmackey commented on src/helpers/calcFixedAPR.ts
> +  timeUntilMaturity: number
👍

2021-07-15 16:10 UTC, smmackey commented on src/helpers/calcFixedAPR.ts
> +): number {
Good catch, edit + unit tests added!

2021-07-15 17:32 UTC, jrhea approved these changes
lgtm

2021-07-15 18:57 UTC, sentilesdal approved these changes
looks great!

2021-07-15 19:55 UTC, merged