Fix spot price bug, add method for base addresses
element-fi/elf-sdk pull request #26
Opened 2021-07-19 22:09 UTC by smmackey

Fixes a bug in spot price calculation. Without taking into consideration the decimals of precision, our calculation for fixed APR can be way off (specifically for USDC).

Also adds a function to obtain the base token address for a given token. This is necessary to help the Twitter bot parse the addresses json in a much slicker fashion.

2021-07-19 22:21 UTC, jrhea requested changes
this is good....just a couple of things to fix

2021-07-19 22:21 UTC, jrhea commented on examples/poolDetails.ts
> +    ptDecimals[0]
Here you can't just assume it is the 0 index.  you need to use the ptIndex variable from line 35 above.

2021-07-19 22:21 UTC, jrhea commented on src/helpers/calcSpotPrice.ts
> +  const diff = 18 - decimals;
maybe just check to make sure that decimals are <= 18

2021-07-19 23:05 UTC, smmackey commented on examples/poolDetails.ts
> +    ptDecimals[0]
Okay, that makes sense 😅 Made the edit!

2021-07-19 23:05 UTC, smmackey commented on src/helpers/calcSpotPrice.ts
> +  const diff = 18 - decimals;
Added in a check for that plus a unit test, but let me know if you think there's a better way to handle that error

2021-07-19 23:13 UTC, jrhea commented on src/helpers/calcSpotPrice.ts
> +  const diff = 18 - decimals;
i think that's good for our purposes.

2021-07-19 23:14 UTC, jrhea commented on examples/poolDetails.ts
> +    ptDecimals[ptIndex]
```suggestion
    ptDecimals[baseIndex]
```

2021-07-19 23:16 UTC, jrhea commented on examples/poolDetails.ts
> +  const ptDecimals = reserves.decimals;
```suggestion
  const baseDecimals = reserves.decimals[baseIndex];
```

2021-07-19 23:16 UTC, jrhea commented on examples/poolDetails.ts
> +    ptDecimals[ptIndex]
```suggestion
   baseDecimals
```

2021-07-20 01:00 UTC, smmackey commented
tests are passing, gonna give it a merge!

2021-07-20 01:00 UTC, merged